"""empty message

Revision ID: 64753b3e8aab
Revises: cdf38b120d80
Create Date: 2025-08-15 17:49:20.892536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64753b3e8aab'
down_revision = 'cdf38b120d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint('book_cover_key', type_='unique')
        batch_op.drop_constraint('book_description_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.create_unique_constraint('book_description_key', ['description'])
        batch_op.create_unique_constraint('book_cover_key', ['cover'])

    # ### end Alembic commands ###
