"""empty message

Revision ID: 7d8c99ef55aa
Revises: 509ea4d73546
Create Date: 2025-08-15 10:26:18.906711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d8c99ef55aa'
down_revision = '509ea4d73546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites_author',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'author_id')
    )
    op.create_table('favorites_books',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'book_id')
    )
    op.drop_table('favorites_autho ')
    op.drop_table('favorites_books ')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites_books ',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name='favorites_books _book_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorites_books _user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'book_id', name='favorites_books _pkey')
    )
    op.create_table('favorites_autho ',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], name='favorites_autho _author_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorites_autho _user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'author_id', name='favorites_autho _pkey')
    )
    op.drop_table('favorites_books')
    op.drop_table('favorites_author')
    # ### end Alembic commands ###
