"""empty message

Revision ID: cdf38b120d80
Revises: 7d8c99ef55aa
Create Date: 2025-08-15 15:56:37.399621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf38b120d80'
down_revision = '7d8c99ef55aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint('book_author_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'author', ['author_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('favorites_author', schema=None) as batch_op:
        batch_op.drop_constraint('favorites_author_author_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_author_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'author', ['author_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('favorites_books', schema=None) as batch_op:
        batch_op.drop_constraint('favorites_books_book_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_books_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'book', ['book_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites_books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_books_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('favorites_books_book_id_fkey', 'book', ['book_id'], ['id'])

    with op.batch_alter_table('favorites_author', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_author_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('favorites_author_author_id_fkey', 'author', ['author_id'], ['id'])

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('book_author_id_fkey', 'author', ['author_id'], ['id'])

    # ### end Alembic commands ###
